// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeo4ovE-oOzF9K78XuSh09J7VQXknPXls',
    appId: '1:756852043560:web:6b70e0b2bc445935ffea1d',
    messagingSenderId: '756852043560',
    projectId: 'qrinfonotification',
    authDomain: 'qrinfonotification.firebaseapp.com',
    storageBucket: 'qrinfonotification.appspot.com',
    measurementId: 'G-ZVX1V6XNWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYeL-5C8MisZy1P75bBy6ji_h1WrDQ1og',
    appId: '1:756852043560:android:3f959f47d99dd161ffea1d',
    messagingSenderId: '756852043560',
    projectId: 'qrinfonotification',
    storageBucket: 'qrinfonotification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmMqfQmHhkT_Dzf37RNbCrrY1F9TcoWhc',
    appId: '1:756852043560:ios:62acdc5ed6798bf4ffea1d',
    messagingSenderId: '756852043560',
    projectId: 'qrinfonotification',
    storageBucket: 'qrinfonotification.appspot.com',
    iosClientId: '756852043560-8vr660i8d5ic9g34nr656vip01o3coee.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrInfo',
  );
}
